### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SeaniaTwix** [SeaniaTwix/community#6]
# Main features
- [x] Route & API endpoint redesign, overhauls. (Follow svelte kit's new routing)
- [ ] Support OAuth
- [ ] Personalized customizable feed
- [ ] Search with conditions of tags (lt, gt...)
- [ ] Supports live streams (public only)
- [ ] More reliable WebSocket subscription logics
- [ ] tRPC
- [ ] Spoiler for comment image
- [ ] User agreements for using each cookie.
- [ ] Add permission based action for each user requests.
- [ ] Tag alias.
- [ ] Native image converter system.
